title: Donghyun Lee (Luke)
description: First-year CS Ph.D. student at UC Berkeley, BAIR, and Sky Computing Lab.
url: "https://lukedhlee.github.io"
baseurl: ""

author:
  name: Donghyun Lee (Luke)
  affiliation: UC Berkeley
  email: ""
  github: lukedhlee
  scholar: ""
  linkedin: ""
  cv: ""

permalink: /blog/:year/:month/:day/:title/
markdown: kramdown

plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
